# Generated by Django 4.1.1 on 2022-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_contas_fornecedores_notas_delete_todo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notas',
            name='numero_nota',
            field=models.IntegerField(),
        ),
    ]
